#ifndef PLUGINSYSTEM_GLOBAL_H
#define PLUGINSYSTEM_GLOBAL_H

#include <QtCore/QObject>

#if defined(PLUGINSYSTEM_LIBRARY)
#  define PLUGINSYSTEM_EXPORT Q_DECL_EXPORT
#else
#  define PLUGINSYSTEM_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINSYSTEM_GLOBAL_H
